"""added subtask check column to task model

Revision ID: 4dcbc3c8ef18
Revises: 3ae8be8a6484
Create Date: 2024-02-22 12:06:34.679989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcbc3c8ef18'
down_revision = '3ae8be8a6484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_subtask', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('has_subtask')

    # ### end Alembic commands ###
